### ISSUE TITLE
Copyright (You are using the Ring programming language source code and removed the original author name!)

### ISSUE THREAD

**Issue by MahmoudFayed** [theratioproject/simple#69]
Hello

The source code of this language (https://github.com/theratioproject/simple/tree/master/simple/sources) and (https://github.com/theratioproject/simple/tree/master/simple/include) is based on the source code of the (Ring programming language)

URL: https://www.codeproject.com/Articles/1089887/The-Ring-Programming-Language
URL: http://ring-lang.net
URL: https://github.com/ring-lang/ring 
URL: https://www.apress.com/gp/book/9781484258323

It's not right to remove the original author name and claim that this is your source code!

To fix this mistake

(1) Add the original author name to each source code file 
(2) Write in the documentation that this language is based on the Ring programming language

We are contacting you first (before contacting github) to avoid reporting the project (And removing it from GitHub)

Greetings,
Mahmoud

**Comment by Thecarisma** [comment]
The project is not been manage any more, is it ok if I add the info in the README file only?

**Comment by MahmoudFayed** [comment]
Yes, Just add this line "This project is based on the source code of the Ring programming language  (http://ring-lang.net) Compiler & VM by Mahmoud Fayed"

**Comment by Thecarisma** [comment]
I have updated the README. I am a big fan of your works I look forward to contributing to some of your projects in future.

**Comment by MahmoudFayed** [comment]
Thanks for the update & Thanks for your kind words
